# Generated by Django 4.2 on 2025-10-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='RecipeIng',
        ),
        migrations.AlterModelOptions(
            name='recipeing',
            options={'default_related_name': 'recipe_ingredients', 'verbose_name': 'Ингредиент Р', 'verbose_name_plural': 'Ингредиенты Р'},
        ),
    ]
